
default: &default
  adapter: postgresql
  pool: 20
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  port: 5432
  username: rails2
  password: rails2
  host: localhost
  database: almacend

test:
  <<: *default
  port: 5432
  username: rails2
  password: rails2
  host: localhost
  database: almacent

production:
  port: 5432
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  username: railwayapp
  password: <%= ENV["RAILWAYAPP_DATABASE_PASSWORD"] %>
  database: railwayapp_production
