default: &default
  adapter: postgresql
  port: 5432
  pool: 20
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  username: rails2
  password: rails2
  host: 127.0.0.1
  database: almacend

test:
  <<: *default
  username: rails2
  password: rails2
  host: 127.0.0.1
  database: almacent

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  database: <%= ENV["PGDATABASE"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV["PGPORT"] %>
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
