default: &default
  adapter: postgresql
  port: 6543
  pool: 20
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  username: rails2
  password: rails2
  host: 127.0.0.1
  database: almacend

test:
  <<: *default
  username: rails2
  password: rails2
  host: 127.0.0.1
  database: almacent

production:
  <<: *default
  host: containers-us-west-149.railway.app
  username: postgres
  password: <%= ENV["PGPASSWORD"] %>
  database: railway
